# Generated by Django 3.0.7 on 2020-07-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(upload_to='test_actors/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='test_movies/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='movieshots',
            name='image',
            field=models.ImageField(upload_to='test_movie_shots/', verbose_name='Изображение'),
        ),
    ]
