# Generated by Django 3.0.7 on 2020-08-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_reviews2_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseForm3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_vk', models.CharField(max_length=100, verbose_name='СсылкаВК')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('question1', models.TextField(max_length=5000, verbose_name='Вопрос1')),
                ('question2', models.TextField(max_length=5000, verbose_name='Вопрос2')),
            ],
            options={
                'verbose_name': 'Запись3',
                'verbose_name_plural': 'Записи3',
            },
        ),
    ]
