# Generated by Django 3.0.7 on 2020-08-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_courseform3'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoulOrMind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_vk', models.CharField(max_length=100, verbose_name='СсылкаВК')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Анкета_ДvsР',
                'verbose_name_plural': 'Анкеты_ДvsР',
            },
        ),
        migrations.AlterModelOptions(
            name='courseform3',
            options={'verbose_name': 'Анкета_3', 'verbose_name_plural': 'Анкеты_3'},
        ),
    ]
